---
  - hosts: dev
    connection: ssh

    tasks:
      - name: file module -create file with permission and owner file

        file:
          path: /root/my-ansa/krishna2.pdf
          state: touch
          owner: krishna
          group: krishna
          mode: "0555"






          

      - name: Delete file---
- hosts: dev
  connection: ssh

  tasks:
    - name: create a file and write content
      copy:
        dest: /root/demo1/demo.pdf
        content:
              Hello world
              i am fine
~                           

        file:
          path: /root/my-ansa/file2
          state: absent






          

~                                                                                         
~                                                                                         
~                 
