---
- hosts: webserver
  become: yes

  tasks:

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy website files to remote machine
      copy:
        src: /root/project2/index.html
        dest: /usr/share/nginx/html/
        owner: nginx
        group: nginx
        mode: '0755'








---
- hosts: dev
  become: yes

  tasks:
    - name: Clone Git repository
      ansible.builtin.git:
        repo: "https://github.com/adityaghaywat-cmd/html.project.git"
        dest: /var/www/html
        version: main

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

        
