---
  - hosts: dev
    connection: ssh

    tasks:
      - name: Install httpd
        command: yum install httpd -y

      - name: Start service
        systemd:
          name: httpd
            # state: started
          state: stopped
            #state: restarted
          enabled: yes
          #daemon_reload: yes













---
- hosts: dev
  connection: ssh

  tasks:
    - name: Install httpd
      command: yum install httpd -y

    - name: Start service
      service:
        name: httpd
        state: started
        state: stopped
        state: restarted
        enabled: yes
        daemon_reload: yes




          

